### ISSUE TITLE
ARC Issue with Xcode 4.5.2

### ISSUE THREAD

**Issue by smolls** [plausiblelabs/plweakcompatibility#2]
There's an issue present with PLWeakCompatibilityStubs.m with the Clang/LLVM combo in the latest Xcode 4.5 release (4.5.2)

```
if (has_mazwr()) {        
    MAZeroingWeakRef *ref = [[MAZWR alloc] initWithTarget: obj];
    *location = (__bridge_retained PLObjectPtr) ref;
    return;
}
```

The MAZWR alloc/init will fail to compile as the compiler now requires that to be defined with either a __bridge or a bridge retain. I initially chose the simpler __bridge option, as the next line does the appropriate ref retain, but want to make sure that's the proper option and that it gets fixed in mainline here :)

**Comment by mikeash** [comment]
I don't see this error here, building the project with Xcode 4.5.2. Are you including additional settings that trigger this?

**Comment by smolls** [comment]
Here's the Xcode error
![Screen Shot 2012-12-27 at 10 24 05 AM](https://f.cloud.github.com/assets/868005/32699/93113950-5039-11e2-83b3-2b9547cbacb7.png)

I used the highlighted suggestion to "fix" the issue. I don't believe we've got any settings out of the ordinary. Here's the linker flags:
![Screen Shot 2012-12-27 at 10 26 51 AM](https://f.cloud.github.com/assets/868005/32711/edfdb298-503a-11e2-8db0-bd655d2c0289.png)

We're compiling against iOS 6 SDK, with a Minimum target version of 4.3, using LLVM 4.1. It's failing to compile in our Debug build, which uses no compiler optimizations (whereas release builds use Fastest & Smallest -0s, and it also fails to compile there). The only C flags are the ones the documentation lists to convince Xcode to compile with weak enabled.

It is compiling the .m using ARC, although I don't see anything in the docs about that being an issue. The issue code  never actually gets hit in our scenario because we're not using the Mazwr lib. 

What other settings might be causing it would you think?

**Comment by mikeash** [comment]
I still can't make the error show up here. Maybe you have a prefix header that's getting in the way somehow? But it may not be necessary. While trying to figure out what was going on, I discovered that the internal prototype for `-initWithTarget:` was declared as a class method! Oops. This is now fixed in commit a9ec557aea7b41f040e29f7eb78210fa9f16bcf4. Pull that down and give it a try. If the error still happens, see what sort of stuff you have in your prefix header, as I suspect there's a conflicting prototype for that method somewhere.

**Comment by smolls** [comment]
Pulled down the commit. That didn't fix it. Did a global search for initWithTarget and, sure enough, we've got some remnants of Three20 in our codebase included in the PCH, and one of those (TTURLNavigatorPattern) has a function
     - (id)initWithTarget:(id)target

Commented that out, and sure enough everything built. Sounds like time for some internal house cleaning (I don't think we use that part of Three20 anymore as we've slowly been moving off it). Thanks for the point in the right direction, and happy to see we at least fixed something :)

**Comment by mikeash** [comment]
Cool, glad you got it worked out. You prompted some much-needed housekeeping on the project even if the problem was elsewhere, so that's good.
