### ISSUE TITLE
Another crash in SwizzledReleaseIMP

### ISSUE THREAD

**Issue by newacct** [plausiblelabs/plweakcompatibility#3]
Hi, I have a crash in SwizzledReleaseIMP at `origIMP(self, _cmd);` in iOS 4.3 simulator similar to #1 . However, it is with the current latest version of PLWeakCompatibility.

To reproduce it, take the tests in the PLWeakCompatibility project, and change the PLWeakCompatibilityEmptyTestSubclass class to add a dealloc method as follows:

```
@implementation PLWeakCompatibilityEmptyTestSubclass
-(void)dealloc {
  id foo = self;
}
@end
```

It crashes with a
`-[PLWeakCompatibilityEmptyTestSubclass release]: unrecognized selector sent to instance` exception (which makes little sense).

I am using the latest released Xcode 4.5.2.

I am not sure whether it is a bug with this version of the compiler (I've seen other ARC bugs), or with PLWeakCompatibility.

**Comment by mikeash** [comment]
Thanks a lot for the report. Based on your description, I was easily able to write a unit test that exposes the bug. It's definitely in PLWeakCompatibility, not a compiler bug. I don't have time to investigate further right at this moment, but will definitely take a look in the next couple of days and get back to you.

**Comment by mikeash** [comment]
Turned out to be a fairly simple fix. Please let me know how it goes and if you have any other trouble.

**Comment by newacct** [comment]
It seems to work now. Thanks
